title: Course
description: "Course @ UvA/MSc-AI"

url: https://nlp-illc.github.io # the base hostname & protocol for your site
baseurl: /course # the subpath of your site, e.g. /course/. Leave blank for root

remote_theme: lorepirri/cayman-blog

header_page_refs:
  - about
  - blog
  - past

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
